/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.5 at Wed Jul 02 16:30:02 2014. */

#include "custom.h"



const pb_field_t ArduinoCustom_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ArduinoCustom__Header_fields[5] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, ArduinoCustom__Header, command, command, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, ArduinoCustom__Header, originator, command, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, CALLBACK, OTHER, ArduinoCustom__Header, nestedPath, originator, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, ArduinoCustom__Header, nestedSpec, nestedPath, 0),
    PB_LAST_FIELD
};

const pb_field_t ArduinoCustom_ping_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ArduinoCustom_testEvents_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ArduinoCustom_serialPrintln_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, ArduinoCustom_serialPrintln, message, message, 0),
    PB_LAST_FIELD
};




