/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.5 at Wed Jul 02 16:30:02 2014. */

#ifndef _PB_CUSTOM_PB_H_
#define _PB_CUSTOM_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

#define HARDWARE_ID_SIZE   64
#define COMMAND1_SIZE      256
#define SYSTEM1_SIZE      256
  
/* Enum definitions */
typedef enum _ArduinoCustom_Command {
    
    ArduinoCustom_Command_RGB_LED = 1,
    ArduinoCustom_Command_DC_MOTOR = 2,
    ArduinoCustom_Command_PING = 3,
    ArduinoCustom_Command_TESTEVENTS = 4,
    ArduinoCustom_Command_SERIALPRINTLN = 5,
      
} ArduinoCustom_Command;

/* Struct definitions */
typedef struct _ArduinoCustom {
    uint8_t dummy_field;
} ArduinoCustom;

typedef struct _ArduinoCustom_ping {
    uint8_t dummy_field;
} ArduinoCustom_ping;
typedef struct _ArduinoCustom_motor {
    char message[100];
} ArduinoCustom_motor;

typedef struct _ArduinoCustom_RGB_SW {
    bool onoff;
} ArduinoCustom_RGB_SW;

typedef struct _ArduinoCustom_RGB_LED {
    int rgbled_h ;
    int rgbled_s;
    int rgbled_b;
} ArduinoCustom_RGB_LED;

typedef struct _ArduinoCustom_DC_MOTOR {
    int motor_sw ;
} ArduinoCustom_DC_MOTOR;

typedef struct _ArduinoCustom_testData {
    int humidity;
    int temperature;
    int infrared;
    int light;
} ArduinoCustom_testData;

typedef struct _ArduinoCustom_testEvents {
    uint8_t dummy_field;
} ArduinoCustom_testEvents;

typedef struct _ArduinoCustom__Header {
    ArduinoCustom_Command command;
    bool has_originator;
    char originator[30];
    pb_callback_t nestedPath;
    pb_callback_t nestedSpec;
} ArduinoCustom__Header;

typedef struct _ArduinoCustom_serialPrintln {
    char message[100];
} ArduinoCustom_serialPrintln;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define ArduinoCustom__Header_command_tag        1
#define ArduinoCustom__Header_originator_tag     2
#define ArduinoCustom__Header_nestedPath_tag     3
#define ArduinoCustom__Header_nestedSpec_tag     4
#define ArduinoCustom_serialPrintln_message_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ArduinoCustom_fields[1];
extern const pb_field_t ArduinoCustom__Header_fields[5];
extern const pb_field_t ArduinoCustom_ping_fields[1];
extern const pb_field_t ArduinoCustom_testEvents_fields[1];
extern const pb_field_t ArduinoCustom_serialPrintln_fields[2];

/* Maximum encoded size of messages (where known) */
#define ArduinoCustom_size                       0
#define ArduinoCustom_ping_size                  0
#define ArduinoCustom_testEvents_size            0
#define ArduinoCustom_serialPrintln_size         102

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
